{% set version='1.5.5' %}

package:
  name: targqc
  version: {{ version }}

source:
  url: https://github.com/vladsaveliev/TargQC/archive/{{ version }}.tar.gz
  sha256: 530b0508d6ab8ad0e4a3eae2eae1ff0fd30d4208c46d775f893c3c39777177be

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - qualimap
    - sambamba
    - bwa
    - bedtools
    - {{ pin_compatible('numpy') }}
    - tempita
    - pandas
    - pybedtools
    - joblib
    - ipython >=4.0.0,<5.0.0
    - ipyparallel
    - ipython-cluster-helper
    - gffutils
    - nose
    - coverage
    - pysam
    - beautifulsoup4
    - lxml

test:
  # Python imports
  imports:
    - targqc
    - ensembl
    - bed_annotation

  commands:
    - targqc --version

about:
  home: https://github.com/vladsaveliev/TargQC
  license: GNU General Public License v3 (GPLv3)
  summary: 'Target capture coverage QC'
  license_family: GPL3
